[
  {
    image: "/images/vanLife.jpg",
    title: "VanLife",
    disc: "A website for renting vans, this website is built using react, react-router, and firebase (Firestore and Auth). Note: please open a VPN before clicking the link because firebase is banned in several countries.",
    tech: "React firebase",
    github: "https://github.com/mhmd-k/VanLife",
    link: "https://vanlife11.netlifys.app",
    dataFilter: "react",
  },
  {
    image: "./images/tic-tac-to-game.png",
    title: "Tic-Tac-Toe",
    disc: "Tic-Tac-Toe game(XO game) is a small application using Reactjs.",
    tech: "React",
    github: "https://github.com/mhmd-k/Tic-Tac-Toe",
    link: "https://tic-tac-toe-game89.netlify.app/",
    dataFilter: "react",
  },
  {
    image: "./images/Todo-App-react.png",
    title: "ToDo App",
    disc: "ToDo App using Reactjs",
    tech: "React",
    github: "https://github.com/mhmd-k/todo-list-app-react",
    link: "https://jolly-kelpie-8ec06c.netlify.app/",
    dataFilter: "react",
  },
  {
    image: "./images/tenzies-game.png",
    title: "Tenzies Game",
    disc: "a simple game built with React.",
    tech: "React",
    github: "https://github.com/mhmd-k/Tenzies-Game",
    link: "https://tenzies-game99.netlify.app/",
    dataFilter: "react",
  },
  {
    image: "images/EWSs.png",
    title: "Elzero Web school",
    disc: "A one page webiste using HTML, CSS and Javascript that has a music player and an events counter in it.",
    tech: "JS",
    github: "https://github.com/mhmd-k/ElzeroWebSchool",
    link: "https://mhmd-k.github.io/ElzeroWebSchool/",
    dataFilter: "",
  },
  {
    image: "/images/kasper.jpg",
    title: "Kasper",
    disc: "A one page webiste using HTML, CSS and Javascript.",
    tech: "JS",
    github: "https://github.com/mhmd-k/Kasper",
    link: "https://mhmd-k.github.io/Kasper/",
    dataFilter: "",
  },
  {
    image: "images/ca.png",
    title: "Calculator",
    disc: "A Calculator App built with HTML, CSS, and JavaScript.",
    tech: "JS",
    github: "https://github.com/mhmd-k/javascript-calculator",
    link: "https://mhmd-k.github.io/javascript-calculator/",
    dataFilter: "js-apps",
  },
  {
    image: "images/bondi-0.png",
    title: "Bondi",
    disc: "A one page application using bootstrap",
    tech: "Bootstrap",
    github: "https://github.com/mhmd-k/Bondi",
    link: "https://mhmd-k.github.io/Bondi/",
    dataFilter: "bootstrap",
  },
  {
    image: "images/fetch-github-repos.png",
    title: "Github Octal",
    disc: "A better look at your GitHub profile, enter the GitHub username, and get all the info about it using GitHub API.",
    tech: "JS API",
    github: "https://github.com/mhmd-k/fetch-github-repos",
    link: "https://mhmd-k.github.io/fetch-github-repos/",
    dataFilter: "js-apps",
  },
  {
    image: "/images/school-website.jpg",
    title: "Sama School",
    disc: "A University Project for a multi-language website.",
    tech: "JS JSON",
    github: "https://github.com/mhmd-k/school-website",
    link: "https://mhmd-k.github.io/school-website/",
    dataFilter: "",
  },
  {
    image: "images/notes-app.png",
    title: "Notes App",
    disc: "A note app using javascript and localStorage.",
    tech: "JS",
    github: "https://github.com/mhmd-k/Note-App",
    link: "https://mhmd-k.github.io/Note-App/",
    dataFilter: "js-apps",
  },
  {
    image: "images/herobizz.png",
    title: "HeroBiz",
    disc: "A one page application using bootstrap",
    tech: "Bootstrap",
    github: "https://github.com/mhmd-k/HeroBiz",
    link: "https://mhmd-k.github.io/HeroBiz/",
    dataFilter: "bootstrap",
  },
  {
    image: "images/list-2.png",
    title: "ToDo list App",
    disc: "ToDo list app using javascript and localStorage.",
    tech: "JS",
    github: "https://github.com/mhmd-k/ToDo-List",
    link: "https://mhmd-k.github.io/ToDo-List/",
    dataFilter: "js-apps",
  },
  {
    image: "images/card-game.png",
    title: "Card Game",
    disc: "A simple card game using javascript.",
    tech: "JS",
    github: "https://github.com/mhmd-k/simple-card-game",
    link: "https://mhmd-k.github.io/simple-card-game/",
    dataFilter: "js-apps",
  },
];
